import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useContext } from 'react';
import styles from '../features/common/styles/Home.module.scss';
import { TodoContext } from '../features/todo/providers/todo_provider';

const Home: NextPage = () => {
  const { state } = useContext(TodoContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href='/posts'>Posts Page</Link>
            <small>（useSWRを試す）</small>
          </li>
          <li>
            <Link href='/counter'>カウンター</Link>
            <small>（useStateを試す）</small>
          </li>
          <li>
            <Link href='/todo'>{`ToDoリスト - ${state.todos.length}件あります`}</Link>
            <small>（useContext, useReducerを試す）</small>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
