import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import styles from '../features/index/styles/index.module.scss';
import { TodoContext } from '../features/todo/providers/todo_provider';

const Home: NextPage = () => {
  const { state } = useContext(TodoContext);
  const { todos } = state;

  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href='/posts'>Posts Page</Link>
            <small>（useSWR、fetchを試す）</small>
          </li>
          <li>
            <Link href='/counter'>カウンター</Link>
            <small>（useStateを試す）</small>
          </li>
          <li>
            <Link href='/todo'>
              {`ToDoリスト - ${todos.length}件中 未完了が${
                todos.filter(t => !t.isDone).length
              }件 あります`}
            </Link>
            <br />
            <small>（useContext, useReducerを試す）</small>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
