import type { NextPageWithLayout } from 'next';
import Head from 'next/head';
import { TitleComponent } from '@/features/common/components/title_component';
import { MainLayout } from '@/features/common/layouts/main_layout';
import { HomeContainer } from '@/features/home/home_container';

const HomePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon.ico' />
      </Head>

      <TitleComponent title='Home Page' />
      <p>pagesの役割はルーティングです。</p>
      <p>Headでtitleを変更、ページの大枠のレイアウト、そしてContainerコンポーネントを呼び出す程度にする。</p>
      <HomeContainer />
    </>
  );
};

HomePage.getLayout = page => <MainLayout>{page}</MainLayout>;

export default HomePage;
